# This file was generated by GoReleaser. DO NOT EDIT.
cask "steadybit" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/steadybit"]
    end
  end

  version "6.0.0"

  on_macos do
    on_arm do
      sha256 "0ef896731c09b252c1175d0c8cc3c17cbadb5e9be3b2a5506f3de7fd38c7d91e"
      url "https://github.com/steadybit/cli/releases/download/v#{version}/steadybit_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "469b6880f15aceb03c4f2f06deb8d33c583f3af063873ea6fb45dbfcccf45039"
      url "https://github.com/steadybit/cli/releases/download/v#{version}/steadybit_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5386146e1df530be1fa700b444bb0ecdf966eea902cf937f16c6673f60d1599d"
      url "https://github.com/steadybit/cli/releases/download/v#{version}/steadybit_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f89870f4aa90284acfc4576aaa78f162353c62e1c242b2d2c026c3b76225a509"
      url "https://github.com/steadybit/cli/releases/download/v#{version}/steadybit_linux_amd64.tar.gz"
    end
  end

  name "steadybit"
  desc "Command-line interface for the Steadybit chaos engineering platform"
  homepage "https://github.com/steadybit/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "steadybit"
  bash_completion "completions/steadybit.bash"
  fish_completion "completions/steadybit.fish"
  zsh_completion "completions/_steadybit"

  # No zap stanza required
end
