# This file was generated by GoReleaser. DO NOT EDIT.
cask "steadybit" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/steadybit"]
    end
  end

  version "6.2.1"

  on_macos do
    on_arm do
      sha256 "b9d48f824d644ea242b7a08b4719602bd66fcced87ed1e519f5ad879f5e0a6e7"
      url "https://github.com/steadybit/cli/releases/download/v#{version}/steadybit_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7ed6dc3ed3f241759a066f94b46c8a8be6631cbe1abc4d44ec02e49e4a87a955"
      url "https://github.com/steadybit/cli/releases/download/v#{version}/steadybit_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4f9a6750b59969003f83147eb4282dacd63db98a99fddcbfdd5da7bc50a473d2"
      url "https://github.com/steadybit/cli/releases/download/v#{version}/steadybit_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e5cd2179824a7a6ee5160721be8876c9674931ce9479c0fefa0ffd3f37db2a0b"
      url "https://github.com/steadybit/cli/releases/download/v#{version}/steadybit_linux_amd64.tar.gz"
    end
  end

  name "steadybit"
  desc "Command-line interface for the Steadybit chaos engineering platform"
  homepage "https://github.com/steadybit/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "steadybit"
  bash_completion "completions/steadybit.bash"
  fish_completion "completions/steadybit.fish"
  zsh_completion "completions/_steadybit"

  # No zap stanza required
end
