# This file was generated by GoReleaser. DO NOT EDIT.
cask "steadybit" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/steadybit"]
    end
  end

  version "6.2.2"

  on_macos do
    on_arm do
      sha256 "75da3391257d45d3ecf5d9ece4a65bbbe45968986f5a5d88b70447f78d9321c2"
      url "https://github.com/steadybit/cli/releases/download/v#{version}/steadybit_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0efdc9c5b7f09abdd916c1dca7f2eb5210b69db14bace85d677537f5ddf51dcd"
      url "https://github.com/steadybit/cli/releases/download/v#{version}/steadybit_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "674ac7857a83549091f9f655e6c86f162605c44efdcf7dd8f0319dd209016544"
      url "https://github.com/steadybit/cli/releases/download/v#{version}/steadybit_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c549f68d56f0e1b4f797ebef6238cc4dd8451efe219f0c7a64befb5bf91ab581"
      url "https://github.com/steadybit/cli/releases/download/v#{version}/steadybit_linux_amd64.tar.gz"
    end
  end

  name "steadybit"
  desc "Command-line interface for the Steadybit chaos engineering platform"
  homepage "https://github.com/steadybit/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "steadybit"
  bash_completion "completions/steadybit.bash"
  fish_completion "completions/steadybit.fish"
  zsh_completion "completions/_steadybit"

  # No zap stanza required
end
